services:

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: posdb
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: "12345"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py start_installation &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ENV=prod
    volumes:
      - media_data:/app/media

volumes:
  postgres_data:
  media_data: